PAGEID=open('page-id.txt').read().strip()
src=open('tracker-before.md',encoding='utf-8').read()
out=src.replace('**Reconciled 2026-09-11 against** **`CLAUDE.md`****, which','**Reconciled 2026-09-11 against `CLAUDE.md`, which',1)
def amend(key, addition):
    global out
    assert out.count(key)==1, key
    i=out.index(key); end=out.index('\n',i); start=out.rindex('\n',0,i)+1
    assert out[start:end].startswith('*   '), out[start:start+60]
    out=out[:end]+' '+addition+out[end:]

i=out.index('## First action'); j=out.index('* * *',i)
out=out[:i]+'''## First action

Run Session 16. New chat:

> Sŏn. Scaling People, session 16. ClickUp task `86ajgmjz6`. Begin.

Session 15 is complete and its page is in the Operating System doc. Session 16 reads the ledger below before anything else. It is the Conclusion and "You" (Book pp. 484 to 503), owned by the People Systems Designer. Its inbound constraints from Sessions 13 to 15: the founders are the partners who hold the leads' check-ins on the team's reading (held on `86akhb2jg`), the reserved-class decision about a person's staying, the center's absorption of a lead's failure, and the counsel questions register; the founders' own performance, a founder as a flag's subject, a founder's departure, the founders' absorber, the partners' place in the pool, and whether a founder on the floor is bound by the live-speech rule are Session 16's. Brandon's values, interiority, working style, and pay are never recorded as positions: Session 16 may propose and must mark every such proposal founder-gated until Brandon confirms it.

'''+out[j:]

i=out.index('**Last session completed:** Session 14'); j=out.index('**Decisions binding a future session:**')
out=out[:i]+f'''**Last session completed:** Session 15, 2026-09-24. Chapter 5, managing managers (how to think about it, individual against manager 1:1s, managing when you are not the expert), managing out, firing, and layoffs (pre-work, the departure conversation at junior and senior levels, legal considerations, gross misconduct, layoffs, and when something bad happens to an employee), and her final thoughts on management, with the workbook's Managing Out Checklist.

**State:** S15 refused "manager development" as a manager of managers and kept it as leading the leads: every act the house already has for every person, applied to a lead on the lead's own sheet by the partner who pairs with the lead, with no one standing above. The monthly lead-and-partner conversation is read as the lead's check-in, and the review, career conversation, window, and flag read with a lead as subject are built on it, all held on `86akhb2jg`. "Manager" leaves the house's vocabulary for any seat, six rules keep the parallel structure parallel, and a lead's failure is absorbed by the center at the partners' review. The separation protocol is three departures and one decision. A departure the person chooses is said to their check-in holder, asked no reason, and recorded as a last day. A departure the house decides is the partners' reserved-class decision with counsel on the hand-off package or a non-negotiable line and nothing else: the failure-mode reference is run on the center's mechanisms first, staying is the default and a real outcome, the record is a closed form in no one's voice, and the partner who took it says it with the check-in holder present, on the clock, in the person's language, with no negotiation. A reduction is a schedule and charter change that is a departure only where a seat is retired with its holder in it and no open move is chosen, and its reason is never a person. Final pay is the days worked and the accrued share; no severance, exit package, or negotiation exists as a mechanism, and "separation payment, if any" is an unset row. The exit interview is the check-in holder's, offered and never required, and is read for the building only; "how people grow beyond the building" is a consented yearly question. The paid hold between a flag read and the partners' review is founder-gated with counsel. Twenty-five counsel questions are listed, and the protocol is designed to run whatever counsel answers. Forty-nine positions: thirty-nine recommended, eight founder-gated, one chef-gated, one team-filled. Readiness rows 183 to 200, so the test stands at two hundred. Twenty-eight instrument specifications, fifteen used and thirteen refused. Thirteen findings inside the record, numbered 13.1 to 13.13; five would surface from a narrow read of the white paper's people pages and eight would not. Page `{PAGEID}`.

'''+out[j:]

hdr='**Decisions binding a future session:**\n\n'
dec='''*   **A person's staying is decided by no one but the partners, on nothing but the package or the line, with counsel, and staying is the default. Binds S16, S17.** The decision about staying is a reserved class at the partners' review. Its inputs are the S14 hand-off package, or a non-negotiable line with the flag's record and the person's own words, and nothing else. Both partners and counsel are present and no one else. The failure-mode reference runs on the center's own mechanisms first, and an unmade fix returns the item. Staying is the default and a real outcome. The record is a closed form in no one's voice about the person. It is never a lead's decision, never a reduction's convenience, never dressed as the person's choice, and never negotiated. S15 names this as the one thing on its page a later session cannot revise at ordinary cost. S15 P22, P23, P38.
*   **Three departures, and a reduction is not a departure until its last step. Binds S16, S17.** The three are a departure the person chooses (said to their check-in holder, no reason asked), a departure the house decides (the decision above), and a reduction of hours or a period that thins or closes, which is a schedule and charter change. A reduction becomes a departure only where a seat is retired with its holder in it and no open move is chosen, and its reason is never a person. A seat with a holder in it is never retired as a retirement. The seasonal shape is stated in advance on the charter, the sheet, and the team home; the reduction's counts are founder-gated (P25). S15 P20, P21, P24, P25.
*   **The departure conversation, final pay, and what the person keeps. Binds S16, S17.** The partner who took the decision says it, with the person's check-in holder present and an interpreter where needed. It happens off the floor, on the clock, in the person's language, in canon's correspondence register, gives no reason beyond the citation, and allows no negotiation. Final pay is the days worked and the accrued share to the last pay date, shown on the pay page. No severance, exit package, negotiation, or withholding exists as a mechanism, and "separation payment, if any" is an unset row on the parameters register, owned by the founders with counsel. The person keeps their pay page, their own words, their competencies as facts, and their relationships. S15 P26 to P28.
*   **After a departure the house says coverage and nothing about the person; the exit interview is read for the building only. Binds S16, S17.** A word about a departed person in any room is a range breach. The exit interview belongs to the person's check-in holder, is offered and never required, is held inside the last scheduled shift on the clock, is written only in the person's words with any of it withheld at their choice, and is read for the building. "How people grow beyond the building" is a consented, once-a-year question to a former team member, withdrawable at any time. S15 P32 to P34, extending S11's exit interview reading.
*   **Leading the leads, and "manager" is not a word for any seat. Binds S16, S17.** A lead's check-in is the monthly lead-and-partner conversation read as a check-in in full, held by the paired partner. The lead's review, career conversation, and window are built on it, and a flag with a lead as subject is read by the other lead and the non-pairing partner. All of it is founder-gated on `86akhb2jg` (P6 to P8, P17, P18). S15 changes S9 11.2's reading that the monthly conversation is not a check-in, and marks the change founder-gated. Six rules keep the structure parallel: one partner per lead's check-in, the alternating chair, nothing about a lead outside the pages, no lead reading the other's people, Class C by domain, and no seat above or between the leads under any load. A lead's failure is absorbed by the center at the partners' review. S15 P2, P4, P6 to P18.
*   **Every legal question is counsel's, on the counsel questions register, and no step marked for counsel runs before its answer. Binds every session.** Twenty-five questions are listed with the protocol step that waits on each and an urgency order: six before the first hire's first paid hour, three before the first flag read, and three before the first charter thins or closes a period. No session asserts employment law, Texas or otherwise. S15 section 14, P46.
*   **The readiness test stands at two hundred rows. Binds every session from here.** Rows 183 to 200 from S15; rows from S16 start at 201. Rows 184, 185, and 188 hold on `86akhb2jg`; 189 on the reserved-class list and the interim rule; 191, 193, and 200 on counsel; 196 reads not yet until the first send; 199 and 200 are read at the first reset as well as the gate. S15 section 11.
'''
assert out.count(hdr)==1; out=out.replace(hdr,hdr+dec)

oq='**Open questions a future session must close:**\n\n'
q='''*   **The counsel questions, in their urgency order.** Twenty-five questions on the counsel questions register: six before the first hire's first paid hour, three before the first flag read, three before the first charter thins or closes a period, and the rest before dinner's gate. Founders, engaging counsel. S15 section 14, P46.
*   **The paid hold between a flag read and the partners' review.** The person is scheduled off, paid at base, with the days counting for the pool, as a schedule state with no reason field. It is not a decision, but it forecloses agency. Founders, with counsel. S15 P29.
*   **The reduction's counts and the seasonal shape.** The stated counts in section 4.5, set at the reset against the first year's counts (P48), and the seasonal shape on the charter's period fields and the sheet's field 11 before the first hire reads either. Founders, with counsel. S15 P25, finding 13.6, `86akh67a1`.
*   **A lead's naming range under a line, and the flag read with a lead as subject.** Founders, with P27's lifetime. S15 P18.
*   **Whether the partners' closed decision record satisfies canon's "documented reason."** Held on the hierarchy ruling. Canon's owner, with the founders. S15 finding 13.5, `86akh3rx4`.
*   **The interim holder of an open lead seat's domain.** The pairing partner holds it as a node-overload line with a closing condition; the co-lead is refused as bundling. A founder load, routed to S16. S15 section 3.
*   **A departing server's regulars.** The relationship is the person's and the record is the house's; the line between them is counsel's. S15 finding 13.8.
'''
assert out.count(oq)==1; out=out.replace(oq,oq+q)

amend("**The decision about a person's staying as a reserved class.**","Designed by S15 as a mechanism (S15 P22, P23, section 10.4, completing S14's incomplete entry); ratification by the founders and counsel's presence remain open.")
amend("**A lead's review holder.**","S15 states the reading in full: the lead's check-in holder, on the same form against the lead's own sheet, with no calibration between the leads' reviews (S15 P7); still on `86akhb2jg`.")
amend("**Who holds a lead's career conversation.**","S15 states the reading: the lead's check-in holder, outward tracks only (S15 P8); still on `86akhb2jg`.")
amend("**Who holds a lead's check-in.**","S15 reads the monthly lead-and-partner conversation as the lead's check-in in full, held by the paired partner, and builds a lead's review, career conversation, window, and flag read on it, all founder-gated here (S15 P6 to P8, P17, P18). This changes S9 11.2's reading that the monthly conversation is not a check-in.")
amend("**The partners' place in the pool, and a departure's final pay.**","S15 closes the departure half as a mechanism: the days worked and the accrued share to the last pay date, with no severance or negotiation as a mechanism and \"separation payment, if any\" as an unset row; timing is counsel's (S15 P27). The partners' place in the pool stays with S16.")
amend("**The exit interview's owner and consent, and post-departure communication.**","Closed by S15 as a mechanism: the exit interview belongs to the person's check-in holder, is offered and never required, and is read for the building only; the \"grow beyond\" measure is a consented yearly question; after a departure the house says coverage and nothing about the person (S15 P32 to P34).")
amend("**Where a non-negotiable breach by a person goes.**","S15 places a breach by a lead (P18) and adds the paid hold (P29, founder-gated); the line's lifetime and the definitions remain open.")
amend("**Who lawfully holds the employment record with no HR seat.**","S15 extends it to the departure record and puts it on the counsel questions register (S15 finding 13.3).")

k="and time in a seat is worth nothing in the record and everything in canon's Jeong and Nunchi."
assert out.count(k)==1
out=out.replace(k,k+" Session 15 found thirteen, five of which would have surfaced from a narrow read of the white paper's people pages and eight of which would not. Among them: the record removed HR into software, names counsel nowhere, and leaves the departure with no lawful holder; \"no disposable people\" has no verb for a departure the house causes; the record fights for every hour and has no account of a season; and blame absorption names no absorber for a lead's failure.")
open('tracker-after.md','w',encoding='utf-8').write(out)
print(len(src.encode()),len(out.encode()))
