#!/usr/bin/env python3
"""Catalog and binding status.

Usage:
  python scripts/status.py            # catalog by stage, and catalog/module disagreements
  python scripts/status.py bindings   # write bindings/registry.md (open bindings grouped by key prefix)
  python scripts/status.py variety    # modality mix across modules
"""
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
ORDER = ["identified", "concept", "designed", "drafted", "reviewed", "parked",
         "bound", "rendered", "published", "measured", "retired", "routed-out"]


def front_matter(path):
    m = re.match(r"^---\n(.*?)\n---", path.read_text(encoding="utf-8"), re.S)
    return (yaml.safe_load(m.group(1)) or {}) if m else {}


def modules():
    for mod in sorted((ROOT / "modules").rglob("module.md")):
        yield mod.parent, front_matter(mod)


def catalog():
    p = ROOT / "catalog" / "catalog.yaml"
    data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    return data.get("modules") or []


def summary():
    rows = catalog()
    by = defaultdict(list)
    for r in rows:
        by[r.get("status", "identified")].append(r)
    print(f"Catalog: {len(rows)} modules\n")
    for st in ORDER:
        if by.get(st):
            print(f"{st} ({len(by[st])})")
            for r in by[st]:
                flag = "" if r.get("confirmed", True) else "  [unconfirmed seed]"
                print(f"  {r['id']:8} {r['title']}{flag}")
    cat = {r["id"]: r.get("status") for r in rows}
    issues = []
    for mdir, meta in modules():
        if meta.get("example"):
            continue
        mid = meta.get("id")
        if mid not in cat:
            issues.append(f"{mid} has a folder but no catalog row")
        elif cat[mid] != meta.get("status"):
            issues.append(f"{mid}: catalog says '{cat[mid]}', module.md says '{meta.get('status')}'")
    if issues:
        print("\nDisagreements:")
        for i in issues:
            print(f"  {i}")


def bindings():
    groups = defaultdict(list)
    total_open = 0
    for mdir, meta in modules():
        bfile = mdir / "bindings.yaml"
        if not bfile.exists():
            continue
        data = yaml.safe_load(bfile.read_text(encoding="utf-8")) or {}
        for b in data.get("bindings") or []:
            if b.get("status") == "filled":
                continue
            total_open += 1
            parts = b["key"].split(".")
            group = ".".join(parts[:2]) if len(parts) > 2 else parts[0]
            groups[group].append((b["key"], meta.get("id"), b.get("gate", "none"), b.get("needs", "")))
    lines = ["# Open bindings", "", "Generated by `python scripts/status.py bindings`. Do not edit by hand.", "",
             f"{total_open} open bindings across {len(groups)} groups. Fill a whole group with `/bind <group>`.", ""]
    for g in sorted(groups):
        lines += [f"## {g}", "", "| Key | Module | Gate | Needs |", "|---|---|---|---|"]
        for key, mid, gate, needs in sorted(groups[g]):
            lines.append(f"| `{key}` | {mid} | {gate} | {needs} |")
        lines.append("")
    out = ROOT / "bindings" / "registry.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}: {total_open} open bindings in {len(groups)} groups")


def variety():
    counts = Counter()
    n = 0
    for mdir, meta in modules():
        media = meta.get("media") or {}
        if not media:
            continue
        n += 1
        for v in set(media.values()):
            counts[v] += 1
    if not n:
        print("No modules with a media plan yet.")
        return
    print(f"Modality mix across {n} module(s):")
    for k, v in counts.most_common():
        print(f"  {v:3}  {k}")
    top = counts.most_common(3)
    share = sum(v for _, v in top) / max(1, sum(counts.values()))
    if n >= 5 and share > 0.75:
        print("\nFlag: three modalities account for most of the program. Revisit framework/modality-library.md.")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "summary"
    {"summary": summary, "bindings": bindings, "variety": variety}.get(cmd, summary)()
